function buildHistoryMenu(kind,key){
 const wrap=document.createElement('div');wrap.className='session-menu-wrap';const more=document.createElement('button');more.className='session-more';more.type='button';more.textContent='⋯';more.setAttribute('aria-label','Opciones de sesión');
 const menu=document.createElement('div');menu.className='session-menu hidden';const edit=document.createElement('button');edit.textContent='Editar sesión';edit.onclick=e=>{e.stopPropagation();menu.classList.add('hidden');editCompletedSession(kind,key)};
 const del=document.createElement('button');del.className='delete';del.textContent='Eliminar sesión';del.onclick=e=>{e.stopPropagation();menu.classList.add('hidden');deleteCompletedSession(kind,key)};
 menu.append(edit,del);more.onclick=e=>{e.stopPropagation();document.querySelectorAll('.session-menu').forEach(m=>{if(m!==menu)m.classList.add('hidden')});menu.classList.toggle('hidden')};wrap.append(more,menu);return wrap
}
document.addEventListener('click',()=>document.querySelectorAll('.session-menu').forEach(m=>m.classList.add('hidden')));
function renderHistory(){
 const h=document.getElementById('historyList');h.innerHTML='';if(!data.history.length&&!data.legacy.length){h.innerHTML='<div class="empty">Todavía no hay sesiones finalizadas.</div>';return}
 [...data.history].reverse().forEach(s=>{
  const r=ROUTINES[s.routineId],c=document.createElement('div');c.className='card history-card';const dur=Number.isFinite(s.durationSec)?` · ${fmtTimer(s.durationSec)}`:'',head=document.createElement('div');head.className='history-head';
  const title=document.createElement('div');title.innerHTML=`<div class="history-title">${r?.day||''} · ${r?.name||s.routineName||'Rutina'}</div><div class="sub">${fmtDateTime(s.startedAt)}${dur}</div>`;head.append(title,buildHistoryMenu('history',s.id||s.startedAt));c.appendChild(head);
  (s.order||Object.keys(s.exercises||{})).forEach(eid=>{const ex=findExercise(s.routineId,eid),st=s.exercises?.[eid];if(!ex||!st||!completedSets(st).length)return;const row=document.createElement('div');row.className='hist-ex';const txt=completedSets(st).map(q=>`${Number.isFinite(q.kg)?q.kg+'kg × ':''}${q.reps}${Number.isFinite(q.rir)?' · RIR '+q.rir:''}`).join(' | ');row.innerHTML=`<span><b>${ex.name}</b><div class="sub">${txt}</div></span><span>${volume(st)!=null?Math.round(volume(st))+' kg':'—'}</span>`;c.appendChild(row)});
  h.appendChild(c)
 });
 if(data.legacy.length){
  const l=document.createElement('div');l.className='section';l.textContent='REGISTROS MIGRADOS DE LA VERSIÓN ANTERIOR';h.appendChild(l);
  [...data.legacy].reverse().forEach(s=>{const c=document.createElement('div');c.className='card history-card',head=document.createElement('div');head.className='history-head',title=document.createElement('div');title.innerHTML=`<div class="history-title">${s.name}</div><div class="sub">${fmtDateTime(s.startedAt)}</div>`;head.append(title,buildHistoryMenu('legacy',s.id||s.startedAt));c.appendChild(head);Object.entries(s.exercises||{}).forEach(([eid,st])=>{if(!completedSets(st).length)return;const row=document.createElement('div');row.className='hist-ex';const txt=completedSets(st).map(q=>`${Number.isFinite(q.kg)?q.kg+'kg × ':''}${q.reps}${Number.isFinite(q.rir)?' · RIR '+q.rir:''}`).join(' | ');row.innerHTML=`<span><b>${anyExerciseName(eid)}</b><div class="sub">${txt}</div></span><span>${volume(st)!=null?Math.round(volume(st))+' kg':'—'}</span>`;c.appendChild(row)});h.appendChild(c)})
 }
}
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
document.getElementById('exportJson').onclick=()=>download('fuerza-backup-v4.json',JSON.stringify(data,null,2),'application/json');
document.getElementById('exportCsv').onclick=()=>{const rows=[['date','routine','exercise','set','kg','reps','rir']];data.history.forEach(s=>Object.entries(s.exercises||{}).forEach(([eid,st])=>completedSets(st).forEach((q,i)=>rows.push([s.startedAt,s.routineId,eid,i+1,q.kg??'',q.reps,q.rir??'']))));download('fuerza-registros.csv',rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')};
document.getElementById('importJson').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());data=normalizeV3(d);save();renderChooser();renderProgress();renderHistory();renderCalendar();toast('Backup importado')}catch{toast('Backup inválido')}e.target.value=''});
document.getElementById('clearAll').onclick=()=>{if(confirm('¿Seguro que quieres borrar rutinas, sesiones programadas, borradores e historial?')){data=blankData();save();showChooser();renderProgress();renderHistory();renderCalendar();toast('Datos borrados')}};
const views={train:document.getElementById('trainView'),progress:document.getElementById('progressView'),calendar:document.getElementById('calendarView'),data:document.getElementById('dataView')},navs={train:document.getElementById('navTrain'),progress:document.getElementById('navProgress'),calendar:document.getElementById('navCalendar'),data:document.getElementById('navData')};
function show(name){Object.entries(views).forEach(([k,v])=>v.classList.toggle('hidden',k!==name));Object.entries(navs).forEach(([k,b])=>b.classList.toggle('active',k===name));const topSession=document.getElementById('sessionTopActions');if(topSession)topSession.classList.toggle('hidden',!(name==='train'&&activeRoutineId&&data.drafts[activeRoutineId]));if(name==='progress'){document.getElementById('progressHome').classList.remove('hidden');document.getElementById('progressDetail').classList.add('hidden');renderProgress()}if(name==='calendar')renderCalendar();if(name==='data')renderHistory()}
navs.train.onclick=()=>{show('train');if(activeRoutineId&&data.drafts[activeRoutineId])renderSession();else showChooser()};navs.progress.onclick=()=>show('progress');navs.calendar.onclick=()=>show('calendar');navs.data.onclick=()=>show('data');
showChooser();renderProgress();renderHistory();renderCalendar();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));